# Generated by Django 3.0 on 2019-12-11 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='desription',
            new_name='description',
        ),
    ]
